"""The vendor check has to actually catch a vendor, not just exit 0.

This is the check standing between `docs/03` and a published score for a vendor
whose terms forbid one. It spent its life as a heredoc that nobody could test
and that only ran when a person ran the gate by hand. Moving it into a script
is worth nothing unless the move is provably faithful, so these tests assert the
catching rather than the passing — a check that has only ever been observed
saying "ok" is indistinguishable from one that always says "ok".

    .venv/bin/python -m unittest discover tests
"""

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import check_vendors  # noqa: E402


def bundle(**parts) -> str:
    payload = {"vendors": [], "all_weeks": {}, "latest": None, **parts}
    return "// Generated by src/export.py — do not edit.\nwindow.SB_DATA = " + \
           json.dumps(payload) + ";\n"


class TestBundleParsing(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.dir = Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def write(self, text: str) -> Path:
        p = self.dir / "bundle.js"
        p.write_text(text)
        return p

    def test_clean_bundle_has_nothing_to_report(self):
        p = self.write(bundle(
            vendors=[{"id": "exa"}, {"id": "serper"}],
            all_weeks={"2026-W31": {"cells": [{"vendor": "linkup", "score": 7.1}]}},
        ))
        self.assertEqual(check_vendors.check_bundle(p), [])

    def test_catches_a_stray_vendor_in_the_vendor_list(self):
        p = self.write(bundle(vendors=[{"id": "exa"}, {"id": "seltz"}]))
        self.assertEqual(check_vendors.check_bundle(p), ["seltz"])

    def test_catches_a_stray_vendor_that_appears_only_in_a_cell(self):
        # The dangerous shape: absent from the list the pages render, but
        # carrying a number in the table. It is still published.
        p = self.write(bundle(
            vendors=[{"id": "exa"}],
            all_weeks={"2026-W31": {"cells": [
                {"vendor": "exa", "score": 8.0},
                {"vendor": "search_router", "score": 6.2},
            ]}},
        ))
        self.assertEqual(check_vendors.check_bundle(p), ["search_router"])

    def test_catches_a_stray_vendor_that_appears_only_in_latest(self):
        p = self.write(bundle(latest={"cells": [{"vendor": "brave", "score": 5.5}]}))
        self.assertEqual(check_vendors.check_bundle(p), ["brave"])

    def test_reports_every_stray_vendor_not_just_the_first(self):
        p = self.write(bundle(vendors=[{"id": "seltz"}, {"id": "brave"}, {"id": "exa"}]))
        self.assertEqual(check_vendors.check_bundle(p), ["brave", "seltz"])

    def test_a_null_latest_is_not_a_crash(self):
        # An export with no publishable week writes latest: null. The check must
        # survive it, because that is exactly when someone is looking at output.
        p = self.write(bundle(latest=None))
        self.assertEqual(check_vendors.check_bundle(p), [])

    def test_a_file_that_is_not_a_bundle_fails_loudly(self):
        p = self.write("window.SOMETHING_ELSE = {};")
        with self.assertRaises(SystemExit):
            check_vendors.check_bundle(p)


class TestRegistryAgreement(unittest.TestCase):
    """The cleared set and REGISTRY are two statements that must agree."""

    def setUp(self):
        self._real = check_vendors.REGISTRY

    def tearDown(self):
        check_vendors.REGISTRY = self._real

    def test_the_repository_currently_agrees_with_itself(self):
        self.assertEqual(check_vendors.check_registry(), [])

    def test_a_vendor_added_to_registry_but_not_cleared_is_caught(self):
        # AUTONOMY.md item 2: adding a key to REGISTRY is the act of putting a
        # vendor in a public benchmark. This is the check that notices.
        check_vendors.REGISTRY = {**self._real, "seltz": (None, "SELTZ_API_KEY")}
        problems = check_vendors.check_registry()
        self.assertEqual(len(problems), 1)
        self.assertIn("seltz", problems[0])
        self.assertIn("REGISTRY", problems[0])

    def test_a_cleared_vendor_dropped_from_registry_is_caught(self):
        # The quieter direction, and still worth failing on: the benchmark would
        # be covering less than docs/03 says it does, with nothing on the page
        # to say so.
        check_vendors.REGISTRY = {k: v for k, v in self._real.items() if k != "linkup"}
        problems = check_vendors.check_registry()
        self.assertEqual(len(problems), 1)
        self.assertIn("linkup", problems[0])

    def test_the_cleared_set_is_not_derived_from_registry(self):
        # If CLEARED were `set(REGISTRY)`, the one commit AUTONOMY.md forbids
        # would also teach this check to approve itself. Pinning the guarantee
        # in a test because it is a property of the design, not of the code as
        # written, and the shortcut is an easy one to take later.
        check_vendors.REGISTRY = {**self._real, "seltz": (None, "SELTZ_API_KEY")}
        self.assertNotIn("seltz", check_vendors.CLEARED)


if __name__ == "__main__":
    unittest.main()
