#!/usr/bin/env python3
"""Generate a synthetic database that exercises the export end to end.

Why this exists: `src/export.py` is the only thing allowed to turn the database
into published numbers, so "does it still run clean" is a correctness gate. But
the database is gitignored — it holds raw vendor payloads (`docs/03`) — so a
fresh checkout, this VPS, and any contributor's laptop all had no way to run
that gate at all. It reported SKIPPED, which verified nothing.

This module closes that hole by generating the input instead of shipping it.
Two constraints shape everything below:

1. **Nothing here may be mistaken for a measurement.** AUTONOMY.md forbids
   fabricating evidence, and a plausible-looking synthetic score is exactly the
   thing that becomes a real-looking number three commits later. So every
   vendor id is prefixed `fixture_`, every query text starts with FIXTURE, every
   URL is under `example.invalid` (an RFC 2606 reserved TLD that cannot
   resolve), the weeks are in 2099, and every run carries a `notes` field
   saying what it is. None of it is ever written into `site/` — the caller
   passes `--out` a temporary directory, and `scripts/check-all.sh` does.

2. **The database itself is never committed.** AUTONOMY.md item 8 is absolute
   about `*.db`, and it is right to be: a binary blob in git is the one artefact
   nobody reviews. The generator is deterministic instead, so the fixture is
   reproducible from source rather than stored — same seed, byte-identical
   logical content, every time.

What it deliberately covers, because these are the export branches that a
single real week never touches:

  * more than one vendor and all six taxonomy categories;
  * complete *and* incomplete judge ensembles, including one (vendor, category)
    cell pushed below `MIN_CELL_COVERAGE` so the suppression path runs;
  * vendor errors, so `n_errors` is non-zero;
  * two runs that fail canonical selection, for the two different reasons it
    can fail — too few queries per category, and too few complete ensembles;
  * two published weeks, so the history-merge and track-record arithmetic run;
  * a `scheduled` trigger, so `track_record.schedule_started` is exercised as
    True somewhere other than in production for the first time.

Usage:
    python scripts/make_fixture_db.py --out /tmp/fx
    python -m src.export --db /tmp/fx/fixture.db --queries /tmp/fx/queries.json \
                         --out /tmp/fx/site
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import storage  # noqa: E402
from src.judge.ensemble import JUDGES  # noqa: E402

# One seed for the whole generator, consumed in a fixed iteration order. The
# fixture has to be a pure function of this file: a check that produces slightly
# different input each run cannot tell a regression from a coin flip.
SEED = 20990101

# Loud on purpose. These strings end up in generated CSVs and JSON, and the only
# protection against one of them being read as a real result later is that it
# cannot be read as one at all.
VENDORS = ["fixture_alpha", "fixture_bravo", "fixture_delta"]

CATEGORIES = ["general_facts", "breaking_news", "local_shopping",
              "code_technical", "multi_hop", "long_tail"]

# Exactly MIN_QUERIES_PER_CATEGORY. Sitting on the boundary rather than safely
# above it means the fixture proves the floor is `>=` and not `>`; a run one
# query short is the smoke test it is meant to reject.
QUERIES_PER_CATEGORY = 10

# Results per response, matching adapters.TOP_K so `n_results` looks like the
# shape the real pipeline produces.
RESULTS_PER_RESPONSE = 10

FIXTURE_NOTE = ("SYNTHETIC FIXTURE generated by scripts/make_fixture_db.py. "
                "Not a measurement. Never publish.")

# Base quality per vendor and adjustment per category, so the exported table has
# a legible shape (a leader, a laggard, a difficulty slope) without any of it
# being a claim about anything. Numbers chosen to keep every score in 0..10.
VENDOR_BASE = {"fixture_alpha": 7.6, "fixture_bravo": 6.4, "fixture_delta": 5.1}
CATEGORY_ADJ = {"general_facts": 1.2, "breaking_news": 0.4, "local_shopping": 0.0,
                "code_technical": -0.4, "multi_hop": -0.9, "long_tail": -1.6}

# Per-family offsets, so `judging.family_spread` and `mean_disagreement` are
# non-null. The real ensemble's whole point is that families disagree; a fixture
# where they agree perfectly would leave that arithmetic untested.
FAMILY_BIAS = {"anthropic": 0.35, "openai": -0.45, "google": 0.1}


def _clamp(x: float) -> float:
    return round(min(10.0, max(0.0, x)), 1)


def query_id(category: str, i: int) -> str:
    return f"fx-{category}-{i:02d}"


def build_queries() -> list[dict]:
    """The fixture query set, in the shape of `src/queries/full-v1.json`.

    Written alongside the database rather than reusing the real set: the export
    joins the database's `queries` table against this file, and pointing a
    synthetic database at the real query ids would produce an export that half
    references real published queries. Keeping both halves fake keeps the
    fixture legible as a fixture.
    """
    out = []
    for cat in CATEGORIES:
        for i in range(1, QUERIES_PER_CATEGORY + 1):
            qid = query_id(cat, i)
            out.append({
                "id": qid,
                "category": cat,
                "source": "fixture-generated",
                "rotates": 1 if cat == "breaking_news" else 0,
                "text": f"FIXTURE QUERY {qid} — synthetic placeholder, not a real question",
                # breaking_news carries no gold answer in the real set either,
                # so the fixture keeps that asymmetry rather than flattening it.
                "gold_answer": None if cat == "breaking_news"
                               else f"FIXTURE REFERENCE ANSWER for {qid}",
            })
    return out


def build_results(vendor: str, qid: str) -> list[dict]:
    """Synthetic retrieved results. `example.invalid` can never resolve."""
    return [
        {
            "rank": r,
            "url": f"https://example.invalid/fixture/{vendor}/{qid}/{r}",
            "title": f"FIXTURE result {r} for {qid}",
            "snippet": f"Synthetic placeholder text for {qid}, rank {r}. "
                       f"No real content was retrieved to produce this.",
        }
        for r in range(1, RESULTS_PER_RESPONSE + 1)
    ]


# --------------------------------------------------------------- run specs

class RunSpec:
    """One run to generate.

    `complete_share` is the share of responses that get a full three-judge
    ensemble; the rest get two, which is what a rate-limit collapse looks like
    in the real data. `suppress` names a (vendor, category) cell that is pushed
    below the coverage floor on purpose.
    """

    def __init__(self, run_id: str, week: str, trigger: str, per_category: int,
                 complete_share: float, n_errors: int = 0,
                 suppress: tuple[str, str] | None = None, why: str = ""):
        self.run_id = run_id
        self.week = week
        self.trigger = trigger
        self.per_category = per_category
        self.complete_share = complete_share
        self.n_errors = n_errors
        self.suppress = suppress
        self.why = why


RUNS = [
    RunSpec("fixrun-2099w01-full", "2099-W01", "manual", QUERIES_PER_CATEGORY, 0.94,
            n_errors=2, suppress=("fixture_delta", "long_tail"),
            why="publishable; carries the suppressed cell and the vendor errors"),
    RunSpec("fixrun-2099w01-smoke", "2099-W01", "manual", 2, 1.0,
            why="rejected: 2 queries per category is below MIN_QUERIES_PER_CATEGORY"),
    RunSpec("fixrun-2099w02-thin", "2099-W02", "manual", QUERIES_PER_CATEGORY, 0.30,
            why="rejected: 30% complete ensembles is below MIN_RUN_COMPLETENESS"),
    RunSpec("fixrun-2099w02-sched", "2099-W02", "scheduled", QUERIES_PER_CATEGORY, 0.98,
            why="publishable, and scheduler-invoked — exercises schedule_started"),
]


def generate(db_path: Path, queries: list[dict]) -> dict:
    rng = random.Random(SEED)
    conn = storage.connect(db_path)

    conn.executemany(
        "INSERT INTO queries (id, category, text, source, gold_answer, gold_urls, rotates) "
        "VALUES (?,?,?,?,?,?,?)",
        [(q["id"], q["category"], q["text"], q["source"], q["gold_answer"],
          json.dumps([f"https://example.invalid/fixture/gold/{q['id']}"]), q["rotates"])
         for q in queries],
    )

    by_category: dict[str, list[dict]] = {}
    for q in queries:
        by_category.setdefault(q["category"], []).append(q)

    summary = []
    for spec in RUNS:
        # Timestamps are fixed strings, not `now()`: canonical selection breaks
        # ties on started_at, so a moving clock would make the choice of
        # published run depend on when the fixture was built.
        hour = 6 + RUNS.index(spec)
        started = f"2099-01-{'04' if spec.week.endswith('W01') else '11'}T{hour:02d}:23:00+00:00"
        conn.execute(
            "INSERT INTO runs (id, started_at, finished_at, week, query_set_hash, "
            "trigger, notes) VALUES (?,?,?,?,?,?,?)",
            (spec.run_id, started, started, spec.week,
             "fixturehash" + "0" * 21, spec.trigger,
             f"{FIXTURE_NOTE} {spec.why}"),
        )

        chosen: list[dict] = []
        for cat in CATEGORIES:
            chosen.extend(by_category[cat][: spec.per_category])

        responses = []
        for q in chosen:
            for vendor in VENDORS:
                responses.append((q, vendor))

        # Which responses are degraded is decided up front from the seeded rng,
        # so the same fixture always has the same holes in the same places.
        n = len(responses)
        idx = list(range(n))
        rng.shuffle(idx)

        error_idx = set(idx[: spec.n_errors])
        # Suppression first: the named cell needs enough incomplete ensembles to
        # land under MIN_CELL_COVERAGE (0.60) on its own, regardless of what the
        # run-wide share does.
        forced_incomplete: set[int] = set()
        if spec.suppress:
            sv, sc = spec.suppress
            cell = [i for i, (q, v) in enumerate(responses)
                    if v == sv and q["category"] == sc and i not in error_idx]
            forced_incomplete.update(cell[: (len(cell) // 2) + 1])

        target_incomplete = int(round(n * (1 - spec.complete_share)))
        incomplete = set(forced_incomplete)
        for i in idx:
            if len(incomplete) >= max(target_incomplete, len(forced_incomplete)):
                break
            if i not in error_idx:
                incomplete.add(i)

        raw_rows, score_rows = [], []
        for i, (q, vendor) in enumerate(responses):
            rid = f"fxresp-{spec.run_id[7:]}-{i:04d}"
            errored = i in error_idx
            base = VENDOR_BASE[vendor] + CATEGORY_ADJ[q["category"]]
            raw_rows.append((
                rid, spec.run_id, q["id"], vendor, "ranked_results",
                None if errored else f"FIXTURE synthesized answer for {q['id']}",
                None if errored else json.dumps(
                    [r["url"] for r in build_results(vendor, q["id"])[:3]]),
                None if errored else json.dumps(build_results(vendor, q["id"])),
                None if errored else 300 + int(rng.random() * 1400),
                0.0 if errored else round(0.001 + rng.random() * 0.004, 5),
                "FIXTURE ERROR: synthetic vendor failure, no request was made"
                if errored else None,
                None,                      # raw_payload: never populated, never exported
                started,
            ))
            if errored:
                continue

            families = [f for f, _ in JUDGES]
            if i in incomplete:
                families = families[:2]    # what a dropped judge call looks like
            # One response per run gets a wide spread, so `responses_over_3pts`
            # is exercised rather than always sitting at zero.
            outlier = (i == idx[-1])
            for fam in families:
                model = dict(JUDGES)[fam]
                jitter = (rng.random() - 0.5) * 2.4
                if outlier and fam == "openai":
                    jitter -= 3.6
                overall = _clamp(base + FAMILY_BIAS[fam] + jitter)
                score_rows.append((
                    f"fxjs-{rid[7:]}-{fam}", rid, model, fam,
                    _clamp(overall + (rng.random() - 0.5)),
                    _clamp(overall + (rng.random() - 0.5)),
                    _clamp(overall + (rng.random() - 0.5)),
                    overall,
                    "FIXTURE rationale — synthetic, no model was called",
                    900 + int(rng.random() * 600),
                    1200 + int(rng.random() * 400),
                    120 + int(rng.random() * 80),
                    started,
                ))

        conn.executemany(
            "INSERT INTO raw_responses (id, run_id, query_id, vendor, response_mode, "
            "answer, citations, results, latency_ms, cost_usd, error, raw_payload, "
            "created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", raw_rows)
        conn.executemany(
            "INSERT INTO judge_scores (id, response_id, judge_model, judge_family, "
            "relevance, freshness, citation_quality, overall, rationale, scored_chars, "
            "prompt_tokens, output_tokens, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
            score_rows)

        summary.append({
            "run_id": spec.run_id, "week": spec.week, "trigger": spec.trigger,
            "responses": len(raw_rows), "judge_scores": len(score_rows),
            "errors": spec.n_errors, "why": spec.why,
        })

    conn.commit()
    conn.close()
    return {"runs": summary, "queries": len(queries), "vendors": VENDORS}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", required=True,
                    help="directory to write fixture.db and queries.json into")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    out = Path(args.out)
    # Refusing outright rather than trusting the caller: this generator writes a
    # database full of invented scores, and the one place it must never be able
    # to write is the directory the published site is built from.
    site = (ROOT / "site").resolve()
    resolved = out.resolve()
    if resolved == site or site in resolved.parents:
        raise SystemExit(f"refusing to write a fixture inside {site} — pass a temp directory")

    out.mkdir(parents=True, exist_ok=True)
    db_path = out / "fixture.db"
    if db_path.exists():
        db_path.unlink()   # regenerate rather than append to a previous fixture

    queries = build_queries()
    (out / "queries.json").write_text(json.dumps({
        "set_name": "fixture-v1",
        "note": (FIXTURE_NOTE + " Every query below is a placeholder string, not a "
                 "question anyone asked, and no vendor was ever sent one."),
        "queries": queries,
    }, indent=1) + "\n")

    info = generate(db_path, queries)
    (out / "README.txt").write_text(
        FIXTURE_NOTE + "\n\n"
        "Regenerate with:  python scripts/make_fixture_db.py --out " + str(out) + "\n")

    if not args.quiet:
        print(f"wrote {db_path}")
        for r in info["runs"]:
            print(f"  {r['run_id']:<24} {r['week']}  {r['trigger']:<9} "
                  f"{r['responses']:>4} responses  {r['judge_scores']:>4} scores")
            print(f"  {'':<24} {r['why']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
